-- Migration: Create tables for synthetic evidence
-- Run this in your Supabase SQL Editor

-- 1. PERMITS TABLE
CREATE TABLE IF NOT EXISTS public.permits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    permit_number TEXT,
    permit_type TEXT,
    status TEXT,
    filed_date TIMESTAMP WITH TIME ZONE,
    issued_date TIMESTAMP WITH TIME ZONE,
    address TEXT,
    neighborhood TEXT,
    business_id TEXT,
    business_name TEXT,
    estimated_cost NUMERIC,
    location JSONB  -- Store lat/lon here
);

-- 2. VIOLATIONS TABLE
CREATE TABLE IF NOT EXISTS public.violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    violation_type TEXT,
    status TEXT,
    date_filed TIMESTAMP WITH TIME ZONE,
    description TEXT,
    address TEXT,
    neighborhood TEXT,
    business_id TEXT,
    business_name TEXT,
    location JSONB
);

-- 3. 311 COMPLAINTS TABLE
CREATE TABLE IF NOT EXISTS public.complaints_311 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    service_request_id TEXT,
    category TEXT,
    status TEXT,
    opened_date TIMESTAMP WITH TIME ZONE,
    closed_date TIMESTAMP WITH TIME ZONE,
    address TEXT,
    neighborhood TEXT,
    business_id TEXT,
    business_name TEXT,
    source TEXT,
    media_url TEXT,
    location JSONB
);

-- 4. SFPD INCIDENTS TABLE
CREATE TABLE IF NOT EXISTS public.sfpd_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    incident_id TEXT,
    category TEXT,
    incident_date TIMESTAMP WITH TIME ZONE,
    resolution TEXT,
    address TEXT,
    neighborhood TEXT,
    business_id TEXT,
    business_name TEXT,
    location JSONB
);

-- Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE public.permits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints_311 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sfpd_incidents ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access (for testing)
CREATE POLICY "Enable read access for all users" ON public.permits FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON public.permits FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.violations FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON public.violations FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.complaints_311 FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON public.complaints_311 FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.sfpd_incidents FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role" ON public.sfpd_incidents FOR INSERT WITH CHECK (true);
